version: "3.0"

services:
  storage-app:
    container_name: storage-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_APPWRITE_ENDPOINT=${NEXT_PUBLIC_APPWRITE_ENDPOINT}
        - NEXT_PUBLIC_APPWRITE_PROJECT=${NEXT_PUBLIC_APPWRITE_PROJECT}
    ports:
      - "3000:3000"
    env_file: 
      - .env
    environment:
      - NODE_ENV=production
    restart: always
